### ISSUE TITLE
Implement project database file and use it in CI to build our website.

### ISSUE THREAD

**Issue by gnulabis** [OHWR/ohwr.org#15]
We need a simple text file that will act as a "database" of projects that are part of OHWR.

In the simplest form, this could be one git repo per line. We could also think of making it a bit more complex, in order to add more info that perhaps does not fit in the YAML project info file that we expect to find at the project repo (if such type of info exists).

Once this file is in our repo, we use it in CI to build the project info pages of our website.

**Comment by vascoguita** [comment]
I'm thinking on what would be the correct approach to this and the following strategy came to my mind, please tell me if you agree:

1. ohwr.org had a .projects.yaml file with the list of projects and maybe some other parameters as you said
2. on a different repository we have the project page generator tool
3. on ohwr.org CI the tool is used to generate the pages according to the .projects.yaml file and create a PR with the pages if there is a change
4. we review and accept the PR

**Comment by gnulabis** [comment]
Sounds good. My extra two cents:

- No need to make the file hidden (the dot at the beginning). This is a core file of the repository, it should be highly visible in my opinion.
-- In this direction, perhaps even a folder called "Projects" with one file per project inside? This could also allow each file to state in its header which metadata version it follows (in case we add new stuff in the future).
- if the generator is elsewhere, then perhaps this whole repo could be CC-BY-SA licensed, no need for BSD-3.
- the generator repo could also include other tools in general, like for example a tool that generates a project file (both the one that goes in ohwr.org and the one that goes in the project repo) based on user-provided input. So it could be called ohwr-tools or something.
- I still see some value in keeping the site and the tools together, because it makes CI easier, less versioning, dependencies etc. And the tools are made for ohwr.org, I don't see them as really reusable.

**Comment by vascoguita** [comment]
Hm, I agree.
On the other hand I also see some value in keeping this repository a pure Hugo project repository.
Maybe this is worth some further discussion.

**Comment by vascoguita** [comment]
Another topic is the language.
There are Yaml tools for many languages.
Should we use python or Bash? https://yaml.org/

**Comment by gnulabis** [comment]
Python, definetely.

**Comment by vascoguita** [comment]
The solution in #19 needs no DB file for the OHWR projects since the list of projects is stored in a variable.
This raises a problem - where is the backup?
I think the place where we store this information and the OHWR website are 2 different problems.
We should decide where to keep an internal catalogue of projects + contacts, etc... Maybe a CERNBox project space?

**Comment by vascoguita** [comment]
This issue has been solved by #19 
The Makefile visits the `projects.txt` file in the root for a list of project urls.
At the moment there is nothing in production, thus the PROJECT_URLS environment variable is used for testing.
