### ISSUE TITLE
Create 'FAQ' page

### ISSUE THREAD

**Issue by vascoguita** [OHWR/ohwr.org#81]
A list of OHWR related FAQs.

**Comment by javier-serrano-pareja** [comment]
I am struggling a bit with this issue. The whole site idea looks quite straight-forward to me. There are of course questions I could make up, like "why did you create the OHR?" but I am not sure those questions would be representative, i.e. close to what visitors ask themselves when they visit the site. Anyway, now more than 600 people received a link to https://ohwr.github.io/ohwr.org/, so I propose we wait a bit and see if we receive any real questions. If we get none after a few weeks, I propose we close this and open a new issue when we do get some questions.

**Comment by vascoguita** [comment]
OK, so for now we don't see a need for a FAQ page yet.
I'll close the issue and if we receive some questions that justify creating FAQs we reopen the issue.
