### ISSUE TITLE
Update 'Home' page

### ISSUE THREAD

**Issue by vascoguita** [OHWR/ohwr.org#82]
Currently the Home page is filled with placeholder content and needs to be updated.

The Home page has the following content:

- [x] The logo - is the current logo the final logo? Are the size and position OK?
- [x] The welcome message - needs to be updated.
- [x] A short description of what OHWR is about - needs to be updated.
- [x] A 'Submit Project' button - is this the main button we want to display on the Home page? Is the position OK?
- [x] A summary of the About page - does it look alright? What about the 'Read More' button? And the image? Are the sizes and position OK?
- [ ] A carousel with of the featured projects - does it look alright? Are the size and position OK? What about the 'Read More' button?
- [x] The latest news - does it look alright? Are 3 latest news enough? Is the disposition good? Are the sizes and the position OK? Are the 'Read More' buttons OK? Does the label of the project they belong to look alright? What about the position and format of the date? Is the 'See All News' button OK?

Add more static content to the Home page if there's anything missing.

**Comment by javier-serrano-pareja** [comment]
I can change the short description. I am OK with the rest, modulo the pending discussion on the carousel of featured projects. This needs the involvement of Maciej, Eva and André, as UX testers, as well. @vascoguita is it OK if I submit a PR with a modified description, but we keep this issue open until we decide on the rest?

**Comment by javier-serrano-pareja** [comment]
For reference, I had a quick discussion with @gnulabis yesterday about UX and the home page. Some quick notes:
- Giving quick access to White Rabbit
  - This is out most visible "community". Rather than creating some kind of "community" concept with only one member so far, it is probably more straight-forward to include a new banner in the Home Page, leading to the main WR project (btw this would correspond to https://ohwr.org/project/white-rabbit/-/wikis/home, but I don't see it in the new site).
- For search to be more useful, we would need two things:
  - Be able to check if we are searching in projects, news, etc. through check boxes or some other means.
  - Display search results in order, with projects first. Most of the time people will be looking for a project. Now we get a lot of news items before and we have to scroll down to projects.

**Comment by vascoguita** [comment]
> I can change the short description. I am OK with the rest, modulo the pending discussion on the carousel of featured projects. This needs the involvement of Maciej, @egousiou and André, as UX testers, as well. @vascoguita is it OK if I submit a PR with a modified description, but we keep this issue open until we decide on the rest?

Yes, we can merge a description and take care of the rest later.

> For reference, I had a quick discussion with @gnulabis yesterday about UX and the home page. Some quick notes:
> 
>     * Giving quick access to White Rabbit
>       
>       * This is out most visible "community". Rather than creating some kind of "community" concept with only one member so far, it is probably more straight-forward to include a new banner in the Home Page, leading to the main WR project (btw this would correspond to https://ohwr.org/project/white-rabbit/-/wikis/home, but I don't see it in the new site).

Just created an issue for this: https://github.com/OHWR/ohwr.org/issues/148

The reason why you can't see white rabbit is that OHWR GitLab returned an error 500 when the tool was reading the description from White Rabbit Wiki. It's rare but it happens some times. It should be over when we move to GitLab.com

> 
>     * For search to be more useful, we would need two things:
>       
>       * Be able to check if we are searching in projects, news, etc. through check boxes or some other means.
>       * Display search results in order, with projects first. Most of the time people will be looking for a project. Now we get a lot of news items before and we have to scroll down to projects.

The search as it is now is indeed useless. For me it's easy to fix the order in which the results are displayed. As to adding check boxes, I will see but it's harder since I'm using a plugin from https://gethugothemes.com.

**Comment by javier-serrano-pareja** [comment]
Thank you @vascoguita, PR with an updated intro sentence for the Home page [here](https://github.com/OHWR/ohwr.org/pull/149). Let me know if you would prefer to keep this issue open for general UX discussion or to close it and spawn other issues as appropriate.

**Comment by vascoguita** [comment]
Thanks Javier, I'm merging the PR as soon as it passes the checks. I'm converting the description of this issue to a checklist and we keep it open until everything is sorted.

**Comment by vascoguita** [comment]
I'm closing this issue although we are not yet sure weather the carousel will stay as it is.
If UX testers propose improvements, we open new issues.
